import os
import json
import zipfile
import shutil
import tempfile
import nbtlib
from typing import Dict, Optional, List

def parse_mcstructure(file_path: str) -> Optional[Dict]:
    """Безопасный парсинг .mcstructure с фиксом ошибок nbtlib (size, TagList)"""
    try:
        data = nbtlib.load(file_path)
        
        # 1. Обработка size (защита от ошибки 'size' на Linux)
        size_data = data.get("size", [0, 0, 0])
        if isinstance(size_data, list):
            x = size_data[0] if len(size_data) > 0 else 0
            y = size_data[1] if len(size_data) > 1 else 0
            z = size_data[2] if len(size_data) > 2 else 0
        else:
            x = size_data.get("x", 0)
            y = size_data.get("y", 0)
            z = size_data.get("z", 0)

        # 2. Обработка палитры и блоков (фикс nbtlib TagList)
        raw_palette = data.get("palette", [])
        if hasattr(raw_palette, "value"):
            palette = raw_palette.value
        else:
            palette = raw_palette

        raw_blocks = data.get("blocks", [])
        if hasattr(raw_blocks, "value"):
            blocks = raw_blocks.value
        else:
            blocks = raw_blocks

        return {
            "size": {"x": x, "y": y, "z": z},
            "palette": palette,
            "blocks": blocks,
            "name": data.get("name", "hologram_build")
        }
    except Exception as e:
        print(f"❌ Ошибка парсинга .mcstructure: {e}")
        return None

def generate_mcaddon(structure_data: Dict) -> Optional[str]:
    """Генерирует .mcaddon с послойными функциями под Armor Stand"""
    if not structure_data:
        return None

    palette = structure_data["palette"]
    blocks = structure_data["blocks"]

    # Создаем временную папку для сборки
    temp_dir = tempfile.mkdtemp()
    pack_dir = os.path.join(temp_dir, "HologramBP")
    func_dir = os.path.join(pack_dir, "functions", "hologram")
    os.makedirs(func_dir, exist_ok=True)

    # 1. Создаем манифест (manifest.json) для Behavior Pack
    manifest = {
        "format_version": 2,
        "header": {
            "name": "Hologram Generator",
            "description": "Generated by Telegram Bot",
            "uuid": "a17e4e30-7c87-4c74-8c21-1bbdef1c1711",
            "version": [1, 0, 0],
            "min_engine_version": [1, 19, 0]
        },
        "modules": [{
            "type": "data",
            "uuid": "b17e4e30-7c87-4c74-8c21-1bbdef1c1712",
            "version": [1, 0, 0]
        }]
    }
    
    with open(os.path.join(pack_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    # 2. Сортировка блоков по слоям (Ось Y) для послойной загрузки
    layers = {}
    for block in blocks:
        # В .mcstructure блок обычно массив: [x, y, z, palette_index]
        if isinstance(block, list) and len(block) >= 4:
            pos_x, pos_y, pos_z, palette_idx = block[0], block[1], block[2], block[3]
            
            # Получаем название блока из палитры и убираем префикс minecraft: для читаемости
            block_name = palette[palette_idx].get("name", "minecraft:air")
            if block_name == "minecraft:air":
                continue

            # Группируем по высоте Y
            if pos_y not in layers:
                layers[pos_y] = []
            
            # Запоминаем команду для этого блока (относительно точки спавна стойки)
            layers[pos_y].append(f"setblock ~{pos_x} ~{pos_y} ~{pos_z} {block_name}")

    if not layers:
        return None

    # 3. Генерируем функции для каждого слоя (Y)
    for y, commands in layers.items():
        layer_file = os.path.join(func_dir, f"layer_{y}.mcfunction")
        with open(layer_file, "w") as f:
            f.write(f"# Блоки слоя Y={y}\n")
            for cmd in commands:
                f.write(cmd + "\n")

    # 4. Генерируем основную функцию summon.mcfunction (спавн стойки и загрузка 1-го слоя)
    # Примечание: Поменяв в коде `/function hologram/layer_0` на layer_1, 
    # вы можете менять отображаемый слой в игре.
    first_layer = sorted(layers.keys())[0] if layers else 0
    summon_file = os.path.join(pack_dir, "functions", "summon.mcfunction")
    with open(summon_file, "w") as f:
        f.write(f"summon armor_stand ~ ~ ~ {{Invisible:1b, NoBasePlate:1b, ShowArms:0b, Tags:[\"hologram_stand\"], Pose:{{Body:[0f,0f,0f]}}}}\n")
        f.write(f"execute as @e[type=armor_stand,tag=hologram_stand,limit=1] at @s run function hologram/layer_{first_layer}\n")
        f.write("### Чтобы сменить слой, выполните в игре:\n")
        f.write("### /function hologram/layer_1, /function hologram/layer_2 и т.д.\n")

    # 5. Упаковываем всё в .mcaddon (архив)
    output_filename = os.path.join(tempfile.gettempdir(), "hologram.mcaddon")
    with zipfile.ZipFile(output_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(pack_dir):
            for file in files:
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, temp_dir)
                zipf.write(full_path, rel_path)

    # Удаляем временную папку после упаковки (она останется в кэше Python, пока не перезапустится бот)
    shutil.rmtree(temp_dir)
    return output_filename
