import os
import json
import zipfile
import shutil
import tempfile
import nbtlib
from typing import Dict, Optional, List, Any

def parse_mcstructure(file_path: str) -> Optional[Dict]:
    """Безопасный парсинг .mcstructure с фиксом ошибок nbtlib"""
    try:
        data = nbtlib.load(file_path)
        
        # Обработка size (защита от падений на Linux)
        size_data = data.get("size", [0, 0, 0])
        if isinstance(size_data, list):
            x = size_data[0] if len(size_data) > 0 else 0
            y = size_data[1] if len(size_data) > 1 else 0
            z = size_data[2] if len(size_data) > 2 else 0
        else:
            x = size_data.get("x", 0)
            y = size_data.get("y", 0)
            z = size_data.get("z", 0)

        # Обработка палитры и блоков (фикс nbtlib TagList)
        raw_palette = data.get("palette", [])
        if hasattr(raw_palette, "value"):
            palette = raw_palette.value
        elif isinstance(raw_palette, list):
            palette = raw_palette
        else:
            palette = []

        raw_blocks = data.get("blocks", [])
        if hasattr(raw_blocks, "value"):
            blocks = raw_blocks.value
        elif isinstance(raw_blocks, list):
            blocks = raw_blocks
        else:
            blocks = []

        return {
            "size": {"x": x, "y": y, "z": z},
            "palette": palette,
            "blocks": blocks,
            "name": data.get("name", "hologram_structure")
        }
    except Exception as e:
        print(f"Ошибка парсинга .mcstructure: {e}")
        return None

def generate_mcaddon(structure_data: Dict) -> Optional[str]:
    """Генерирует .mcaddon на основе данных структуры"""
    if not structure_data:
        return None

    size = structure_data["size"]
    palette = structure_data["palette"]
    blocks = structure_data["blocks"]

    # Создаем временную папку для сборки
    temp_dir = tempfile.mkdtemp()
    pack_dir = os.path.join(temp_dir, "HologramBP")
    func_dir = os.path.join(pack_dir, "functions")
    os.makedirs(func_dir, exist_ok=True)

    # 1. Создаем manifest.json для Behavior Pack
    manifest = {
        "format_version": 2,
        "header": {
            "name": "Hologram Generator",
            "description": "Generated by Telegram Bot",
            "uuid": "a17e4e30-7c87-4c74-8c21-1bbdef1c1711", # Генерируем статичный UUID
            "version": [1, 0, 0],
            "min_engine_version": [1, 19, 0]
        },
        "modules": [{
            "type": "data",
            "uuid": "b17e4e30-7c87-4c74-8c21-1bbdef1c1712",
            "version": [1, 0, 0]
        }]
    }
    
    with open(os.path.join(pack_dir, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    # 2. Генерируем функцию (.mcfunction)
    func_path = os.path.join(func_dir, "summon.mcfunction")
    with open(func_path, "w") as f:
        # Спавним стойку для брони
        f.write("summon armor_stand ~ ~ ~\n")
        # Если нужно получить UUID стойки, нужно использовать /tag или /data get, здесь упростим
        f.write("tag @e[type=armor_stand,limit=1,sort=nearest] add hologram_root\n")
        
        # Записываем координаты блоков
        f.write("### Блоки структуры:\n")
        
        # --- ЗДЕСЬ ТЕБЕ НУЖНО ВСТАВИТЬ ТВОЮ ЛОГИКУ ПЕРЕБОРА БЛОКОВ (PALETTE + BLOCKS) ---
        # Я даю ПРИМЕР того, как это сделать, но тебе нужно будет дописать 
        # парсинг "палитры" (коды блоков) в зависимости от смещения по Y.
        
        for block_pos in blocks:
            # block_pos - это позиция блока внутри файла структуры (x, y, z)
            # Тут происходит магия получения имени блока из палитры по индексу.
            # Покажу абстрактную логику (заглушка):
            f.write(f"setblock ~{block_pos[0]} ~{block_pos[1]} ~{block_pos[2]} air\n")
            
        f.write("### ЗАМЕНИ ЭТОТ БЛОК НА ФУНКЦИЮ ПЕРЕБОРА БЛОКОВ")

    # 3. Упаковываем всё в .mcaddon
    output_filename = os.path.join(tempfile.gettempdir(), "hologram.mcaddon")
    with zipfile.ZipFile(output_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files in os.walk(pack_dir):
            for file in files:
                full_path = os.path.join(root, file)
                rel_path = os.path.relpath(full_path, temp_dir)
                zipf.write(full_path, rel_path)

    # Удаляем временную папку
    shutil.rmtree(temp_dir)
    return output_filename
